# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'examples/dummy.ui'
#
# Created: Mon Mar  9 11:47:00 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DummyWidget(object):
    def setupUi(self, DummyWidget):
        DummyWidget.setObjectName(_fromUtf8("DummyWidget"))
        DummyWidget.resize(867, 833)
        self.verticalLayout_13 = QtGui.QVBoxLayout(DummyWidget)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.splitter = QtGui.QSplitter(DummyWidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.mapFrame = QtGui.QFrame(self.splitter)
        self.mapFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mapFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mapFrame.setObjectName(_fromUtf8("mapFrame"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.mapFrame)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.mapLayout = QtGui.QVBoxLayout()
        self.mapLayout.setObjectName(_fromUtf8("mapLayout"))
        self.verticalLayout_15.addLayout(self.mapLayout)
        self.frame_6 = QtGui.QFrame(self.splitter)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame = QtGui.QFrame(self.frame_6)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.toolButton = QtGui.QToolButton(self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icon.svgz")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(32, 32))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.verticalLayout_4.addWidget(self.toolButton)
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_4.addWidget(self.pushButton)
        self.radioButton = QtGui.QRadioButton(self.frame)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout_4.addWidget(self.radioButton)
        self.checkBox = QtGui.QCheckBox(self.frame)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_4.addWidget(self.checkBox)
        self.progressBar = QtGui.QProgressBar(self.frame)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_4.addWidget(self.progressBar)
        self.spinBox = QtGui.QSpinBox(self.frame)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.verticalLayout_4.addWidget(self.spinBox)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.verticalLayout_4.addWidget(self.doubleSpinBox)
        self.dateEdit = QtGui.QDateEdit(self.frame)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.verticalLayout_4.addWidget(self.dateEdit)
        self.dial = QtGui.QDial(self.frame)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.verticalLayout_4.addWidget(self.dial)
        self.verticalSlider = QtGui.QSlider(self.frame)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.verticalLayout_4.addWidget(self.verticalSlider)
        self.horizontalLayout.addWidget(self.frame)
        self.scrollArea = QtGui.QScrollArea(self.frame_6)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 518, 779))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setMinimumSize(QtCore.QSize(500, 179))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableView = QtGui.QTableView(self.groupBox_3)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setShowGrid(False)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayout_2.addWidget(self.tableView)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setMinimumSize(QtCore.QSize(500, 179))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.treeView = QtGui.QTreeView(self.groupBox_2)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.verticalLayout_3.addWidget(self.treeView)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setMinimumSize(QtCore.QSize(500, 179))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.listView = QtGui.QListView(self.groupBox)
        self.listView.setAlternatingRowColors(True)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.verticalLayout.addWidget(self.listView)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.tabWidget = QtGui.QTabWidget(self.frame_6)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.frame_3 = QtGui.QFrame(self.tab_2)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.toolButton_5 = QtGui.QToolButton(self.frame_3)
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.verticalLayout_11.addWidget(self.toolButton_5)
        self.pushButton_5 = QtGui.QPushButton(self.frame_3)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout_11.addWidget(self.pushButton_5)
        self.radioButton_5 = QtGui.QRadioButton(self.frame_3)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.verticalLayout_11.addWidget(self.radioButton_5)
        self.checkBox_5 = QtGui.QCheckBox(self.frame_3)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.verticalLayout_11.addWidget(self.checkBox_5)
        self.verticalLayout_12.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.comboBox = QtGui.QComboBox(self.frame_2)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.verticalLayout_6.addWidget(self.comboBox)
        self.toolButton_2 = QtGui.QToolButton(self.frame_2)
        self.toolButton_2.setCheckable(True)
        self.toolButton_2.setChecked(True)
        self.toolButton_2.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.verticalLayout_6.addWidget(self.toolButton_2)
        self.lineEdit = QtGui.QLineEdit(self.frame_2)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_6.addWidget(self.lineEdit)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.frame_2)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout_6.addWidget(self.plainTextEdit)
        self.textEdit = QtGui.QTextEdit(self.frame_2)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_6.addWidget(self.textEdit)
        self.pushButton_2 = QtGui.QPushButton(self.frame_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.radioButton_2 = QtGui.QRadioButton(self.frame_2)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout_6.addWidget(self.radioButton_2)
        self.checkBox_2 = QtGui.QCheckBox(self.frame_2)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.verticalLayout_6.addWidget(self.checkBox_2)
        self.horizontalSlider = QtGui.QSlider(self.frame_2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.verticalLayout_6.addWidget(self.horizontalSlider)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_13.addWidget(self.splitter)
        self.actionReloadStyle = QtGui.QAction(DummyWidget)
        self.actionReloadStyle.setObjectName(_fromUtf8("actionReloadStyle"))

        self.retranslateUi(DummyWidget)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DummyWidget)

    def retranslateUi(self, DummyWidget):
        DummyWidget.setWindowTitle(_translate("DummyWidget", "Form", None))
        self.toolButton.setToolTip(_translate("DummyWidget", "Exampe tool tip", None))
        self.toolButton.setStatusTip(_translate("DummyWidget", "Exampe tool tip", None))
        self.toolButton.setText(_translate("DummyWidget", "...", None))
        self.pushButton.setText(_translate("DummyWidget", "PushButton", None))
        self.radioButton.setText(_translate("DummyWidget", "RadioButton", None))
        self.checkBox.setText(_translate("DummyWidget", "CheckBox", None))
        self.groupBox_3.setTitle(_translate("DummyWidget", "Table", None))
        self.groupBox_2.setTitle(_translate("DummyWidget", "Tree", None))
        self.groupBox.setTitle(_translate("DummyWidget", "List", None))
        self.toolButton_5.setText(_translate("DummyWidget", "...", None))
        self.pushButton_5.setText(_translate("DummyWidget", "PushButton", None))
        self.radioButton_5.setText(_translate("DummyWidget", "RadioButton", None))
        self.checkBox_5.setText(_translate("DummyWidget", "CheckBox", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DummyWidget", "Tab 2", None))
        self.toolButton_2.setText(_translate("DummyWidget", "sfdsdffdgf", None))
        self.lineEdit.setText(_translate("DummyWidget", "sfdgsdffdd", None))
        self.plainTextEdit.setPlainText(_translate("DummyWidget", "sasdsdf\n"
"sdfsfdg\n"
"sdfsdfgfd\n"
"\n"
"\n"
"dafdfd", None))
        self.textEdit.setHtml(_translate("DummyWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">sasdsdf</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" text-decoration: underline;\">sdfsfdg</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">sdfsdfgfd</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">dafdfd</span></p></body></html>", None))
        self.pushButton_2.setText(_translate("DummyWidget", "PushButton", None))
        self.radioButton_2.setText(_translate("DummyWidget", "RadioButton", None))
        self.checkBox_2.setText(_translate("DummyWidget", "CheckBox", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DummyWidget", "Tab 1", None))
        self.actionReloadStyle.setText(_translate("DummyWidget", "reloadStyle", None))
        self.actionReloadStyle.setShortcut(_translate("DummyWidget", "Alt+R", None))

